name: CI

on:
  push:
    branches-ignore:
      - 'master'

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Go Mod
        run: go mod download && go mod vendor

      - name: Unit Tests
        run: sudo go test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker data directory
        run: sudo mkdir -p /docker-data

      - name: Build rootfs
        run: sudo ./scripts/build.sh "ci"

      - name: Install plugin
        run: sudo ./scripts/install.sh "ci"

      - name: Integration Tests
        run: sudo ./scripts/integration_test.sh "ci"